#!/bin/bash
function title() {
  TitleBorder="*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*"
  echo ""
  echo $TitleBorder
  echo ""
  echo "  "$1
  echo ""
  echo $TitleBorder
  echo ""
}

title "Upgrading the system"

apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get upgrade -y

title "Installing PPAs"

#add-apt-repository -y ppa:ondrej/php5
add-apt-repository -y ppa:webupd8team/atom
#add-apt-repository -y ppa:webupd8team/themes
add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora
add-apt-repository -y ppa:webupd8team/sublime-text-3

title "Installing Software"

apt-get update

## install everything
apt-get install -y apache2 php7.0 mariadb-server phpmyadmin mysql-workbench \
nodejs npm atom vim filezilla firefox openjdk-9-jre chromium-browser virtualbox \
sublime-text-installer i3
